spring.application.name=sacabam-clicker-be

# --- DATABASE CONFIGURATION (Supabase) ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA CONFIG ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# 1. Yêu c?u Hibernate gi? nguyên tên b?ng/c?t nh? ?ã khai báo trong code
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# 2. B?t Hibernate ph?i thêm d?u ngo?c kép vào m?i câu l?nh SQL g?i ?i
# ?i?u này c?c k? quan tr?ng ?? Postgres hi?u ?úng "GameProfiles" thay vì gameprofiles
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# --- App Config ---
server.port=8080

# --- HIKARI CONFIG ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=1800000

# --- API URL Config ---
# T?t c? API s? t? ??ng có ti?n t? /api/v1
server.servlet.context-path=/
spring.mvc.servlet.path=/
# (Ho?c dùng c?u hình d??i ?ây tùy phiên b?n Spring)
spring.web.error.path=/error
spring.data.rest.base-path=/api/v1